install.packages(c("gdata", "foreign", "SASxport", "sas7bdat", "mvtnorm", "rpart", "pwr", "nnet", "elasticnet", "foreach", "doParallel"))
library(gdata)
library(foreign)
library(SASxport)
library(sas7bdat)
library(mvtnorm)
library(rpart)
library(pwr)
library(nnet)
library(elasticnet)
library(foreach)
library(doParallel)